#source("subsetFile.R")
png("plot3.png")
hp <- read.csv("hp.txt", sep=";", header=TRUE)
with(hp, plot(Sub_metering_1, type="n", ylab="Energy sub metering", xlab=NA,xaxt="n"))
with(hp, lines(Sub_metering_1))
with(hp, lines(Sub_metering_2, col="red"))
with(hp, lines(Sub_metering_3, col="blue"))
mtext("Fri", side=1)
mtext("Thu", side=1, adj=0)
mtext("Sat", side=1, adj=1)
legend("topright", lty=c(1,1,1), col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
